version: "2"
services:
  app:
    image: "swisstopo/${SERVICE_NAME}:local"
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      - LOGGING_CFG
  s3:
    image: minio/minio
    env_file: ./minio.env
    command: server /data
    volumes:
      - type: bind
        source: ${PWD}/.volumes/minio
        target: /data
    ports:
      - 9090:9000
